-- epf_pmos_96_full canonical schema.
-- 业务字段与 data/96/authoritative/pmos_96_全量.csv 完全一致。
-- unit_id/source_captured_at 是数据库审计元数据，不属于数据集业务字段。
CREATE TABLE IF NOT EXISTS `epf_pmos_96_full` (
    `id` BIGINT NOT NULL AUTO_INCREMENT COMMENT '数据库技术主键',
    `market_date` DATE NOT NULL COMMENT '数据集字段: market_date',
    `时段` VARCHAR(5) NOT NULL COMMENT '数据集字段: 时段，00:15..24:00',
    `直调负荷预测` DECIMAL(14,4) DEFAULT NULL,
    `地方电厂出力预测` DECIMAL(14,4) DEFAULT NULL,
    `外电预测` DECIMAL(14,4) DEFAULT NULL,
    `风电预测` DECIMAL(14,4) DEFAULT NULL,
    `光伏预测` DECIMAL(14,4) DEFAULT NULL,
    `核电预测` DECIMAL(14,4) DEFAULT NULL,
    `自备电厂预测` DECIMAL(14,4) DEFAULT NULL,
    `试验机组预测` DECIMAL(14,4) DEFAULT NULL,
    `全网负荷预测` DECIMAL(14,4) DEFAULT NULL COMMENT 'ForecastData.qwfh',
    `直调负荷实际` DECIMAL(14,4) DEFAULT NULL,
    `地方电厂出力实际` DECIMAL(14,4) DEFAULT NULL,
    `外电实际` DECIMAL(14,4) DEFAULT NULL,
    `风电实际` DECIMAL(14,4) DEFAULT NULL,
    `光伏实际` DECIMAL(14,4) DEFAULT NULL,
    `核电实际` DECIMAL(14,4) DEFAULT NULL,
    `自备电厂实际` DECIMAL(14,4) DEFAULT NULL,
    `试验机组实际` DECIMAL(14,4) DEFAULT NULL,
    `抽蓄实际` DECIMAL(14,4) DEFAULT NULL,
    `全网负荷实际` DECIMAL(14,4) DEFAULT NULL COMMENT 'RealityData.qwfh',
    `直调负荷临时实际` DECIMAL(14,4) DEFAULT NULL COMMENT 'RealityTmpData',
    `地方电厂出力临时实际` DECIMAL(14,4) DEFAULT NULL COMMENT 'RealityTmpData',
    `外电临时实际` DECIMAL(14,4) DEFAULT NULL COMMENT 'RealityTmpData',
    `风电临时实际` DECIMAL(14,4) DEFAULT NULL COMMENT 'RealityTmpData',
    `光伏临时实际` DECIMAL(14,4) DEFAULT NULL COMMENT 'RealityTmpData',
    `核电临时实际` DECIMAL(14,4) DEFAULT NULL COMMENT 'RealityTmpData',
    `自备电厂临时实际` DECIMAL(14,4) DEFAULT NULL COMMENT 'RealityTmpData',
    `试验机组临时实际` DECIMAL(14,4) DEFAULT NULL COMMENT 'RealityTmpData',
    `抽蓄临时实际` DECIMAL(14,4) DEFAULT NULL COMMENT 'RealityTmpData',
    `全网负荷临时实际` DECIMAL(14,4) DEFAULT NULL COMMENT 'RealityTmpData.qwfh',
    `边界全网负荷预测` DECIMAL(14,4) DEFAULT NULL COMMENT 'ForecastBoundaryData.qwfh',
    `边界直调负荷预测` DECIMAL(14,4) DEFAULT NULL COMMENT 'ForecastBoundaryData.zdfh',
    `边界外电预测` DECIMAL(14,4) DEFAULT NULL COMMENT 'ForecastBoundaryData.llxfh',
    `边界风电预测` DECIMAL(14,4) DEFAULT NULL COMMENT 'ForecastBoundaryData.fd',
    `边界光伏预测` DECIMAL(14,4) DEFAULT NULL COMMENT 'ForecastBoundaryData.gf',
    `边界核电预测` DECIMAL(14,4) DEFAULT NULL COMMENT 'ForecastBoundaryData.hd',
    `日前一次出清价格` DECIMAL(14,4) DEFAULT NULL COMMENT '补充字段：日前首次发布/一次出清96点价格',
    `日前出清价格` DECIMAL(14,4) DEFAULT NULL COMMENT '现有主字段：日前二次出清/最终版价格',
    `日前出力` DECIMAL(14,4) DEFAULT NULL,
    `日前电量` DECIMAL(14,4) DEFAULT NULL,
    `日前开机状态` VARCHAR(20) DEFAULT NULL,
    `日前电源类型` VARCHAR(64) DEFAULT NULL,
    `实时出清价格` DECIMAL(14,4) DEFAULT NULL,
    `实时出力` DECIMAL(14,4) DEFAULT NULL,
    `实时电量` DECIMAL(14,4) DEFAULT NULL,
    `实时开机状态` VARCHAR(20) DEFAULT NULL,
    `实时电源类型` VARCHAR(64) DEFAULT NULL,
    `正备用预测` DECIMAL(14,4) DEFAULT NULL,
    `负备用预测` DECIMAL(14,4) DEFAULT NULL,
    `unit_id` VARCHAR(64) NOT NULL COMMENT '数据库元数据：价格对应的机组ID',
    `source_captured_at` DATETIME DEFAULT NULL COMMENT '数据库元数据：原始包采集时间',
    `create_time` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `update_time` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_full_date_period_unit` (`market_date`, `时段`, `unit_id`),
    KEY `idx_full_market_date` (`market_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='PMOS 96点宽表：业务字段与权威CSV一致';
